FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build-env
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet build -c Release -o ./output

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-alpine AS runtime-env
WORKDIR /app
COPY --from=build-env /app/output .